@startuml diagrama-execucao-testes
skinparam dpi 200
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam defaultTextAlignment center
skinparam shadowing false
skinparam ArrowColor #333333
skinparam ActivityBorderColor #333333
skinparam ActivityBackgroundColor #EEEEEE
skinparam ActivityDiamondBorderColor #333333
skinparam ActivityDiamondBackgroundColor #DDDDDD
skinparam ActivityStartColor #333333
skinparam ActivityEndColor #333333

start
:Construir imagem do contêiner;
while (Há algoritmo a executar?) is (Sim)
  :Iniciar contêiner;
  :Executar algoritmo em **Rust**
  com coleta de métricas;
  :Reiniciar contêiner;
  :Executar algoritmo em **Wasm**
  com coleta de métricas;
  :Parar contêiner;
  :Formatar métricas;
endwhile (Não)
stop
@enduml
